---
# ============================================================
# Role: common — Handlers
# ============================================================

- name: reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system
  become: true
  changed_when: false

- name: reload ufw
  community.general.ufw:
    state: enabled
  become: true

- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    daemon_reload: false
  become: true

- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
    daemon_reload: false
  become: true
