{{- if .Values.playground.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "promptforge.fullname" . }}-playground
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promptforge.labels" . | nindent 4 }}
    app.kubernetes.io/component: playground
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: playground
    {{- include "promptforge.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.playground.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
